---
# ====== Application: Tmdb5000b ==============================
identification: 
  name: Tmdb5000b
  alias: TMDB5000B
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 52608361737335296083

authorization: 
  authorization-scheme: Reader Rights # 52608369266161296096
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: WKSP_SHYED2001

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Tmdb5000b

progressive-web-app: 
  enable: true
  installable: true
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: true
  pwa-push-notifications-credentials: App 200942 Push Notifications Credentials # 52608691306333297182

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 52608362506319296084

navigation-bar: 
  implementation: List
  list: Navigation Bar # 52608363785957296086
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 15629547254268

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Tmdb5000b

component-settings: 
- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 52608357228647296078
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 15629546018450

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 52608357562462296080
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 15629546018481

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 52608357850651296080
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 15629546018492

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 52608358120123296080
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 15629546018497

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 52608358454527296081
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 15629546018497

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 52608358775045296081
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 15629546018500

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 52608359073897296081
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 15629546018504

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 52608359304146296081
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 15629546018507

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 52608359643279296081
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 15629546018508

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 52608359951808296081
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 15629546018519

- # ====== Component Setting: NATIVE_IR ========================
  id: 52608360286625296082
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 15629546018524

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 52608360582049296082
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 15629546018524

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 52608360898792296082
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15629546018532

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 52608361109828296082
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 15629546018539

application-settings: 
- # ====== Application Setting: FEEDBACK_ATTACHMENTS_YN ========
  id: 52608370168958296098
  identification: 
    name: FEEDBACK_ATTACHMENTS_YN

  value: 
    value: Y
    required: false

  advanced: 
    valid-values: Y, N
    on-upgrade-keep-value: true

  subscription: 
    version-number: 15629546018928

  configuration: 
    build-option: 'Feature: Feedback' # 52608366591039296092

- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 52608370493552296099
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ACL_ONLY
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  subscription: 
    version-number: 15629546018957

  configuration: 
    build-option: 'Feature: Access Control' # 52608366355375296092

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

